"""Adiciona campo created_at aos models

Revision ID: d7faa9d985e7
Revises: b83ecc1cdd41
Create Date: 2025-08-31 13:37:17.811340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7faa9d985e7'
down_revision: Union[str, Sequence[str], None] = 'b83ecc1cdd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('categorias', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('centros_treinamento', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centros_treinamento', 'created_at')
    op.drop_column('categorias', 'created_at')
    op.drop_column('atletas', 'created_at')
    # ### end Alembic commands ###
